# NUMPY

# INTRODUCTION

1) NumPy is a Python Library.

2) NumPy is used for working with arrays.

3) NumPy is short for "Numerical Python".

# What is NumPy

1) NumPy stands for numeric python which is a python packages for the comptation and processing of the multidimensional and single dimensional array elements.

it is majorly helpful for the matrics and it is majorly helpful for the Arrays.

open source - package - optimal computation

optimal computation- majorly helpful for the computer vision.

# Why NUMPY

1) In python we have lists that serve the purpose of arrays, but they are slow to process.

2) NumPy aims to provide an array object that is up to 50x faster than traditional python lists.

3) The array object in Numpy is Called ndarray. It provides a lot of supporting functions That make
working with ndarray very easy.

4) Arrays are very frequently used in data science,where speed and resources are very important.

In [1]:
!pip install numpy

In [2]:
import numpy as np

In [3]:
# numpy array single dimensional array

a=np.array([1,2,3,4,5,6,7,8])
print(a)
print(type(a))

[1 2 3 4 5 6 7 8]
<class 'numpy.ndarray'>


In [4]:
a[4]

5

In [5]:
print(a[5])

6


In [6]:
a.shape  # 8 item present in the list

(8,)

In [7]:
#  numpy array two dimensional array

b=np.array([[1,2,3,4,5,],[6,7,8,9,10]])
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [8]:
print(b[0,3])
print(b[1,3])

4
9


In [9]:
b.shape  # rows and columns display

(2, 5)

In [10]:
# array Slicing 

b=np.array([[1,2,3,4,5,],[6,7,8,9,10]])
b[0,1:4]

array([2, 3, 4])

In [11]:
b[1,2:5]

array([ 8,  9, 10])

In [12]:
# data type     - int float bool

c=np.array([[1,2,3,4,5,],[6,7,8,9,10]],dtype='float')
c

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.]])

In [13]:
# astype- its to convert datatype one to another in array

# newarr=a.astype('i')
newarr=a.astype("float")
# newarr=a.astype("int")
# newarr=a.astype("bool")
print(newarr)

[1. 2. 3. 4. 5. 6. 7. 8.]


In [14]:
# 1D-2D reshape

arr=np.array([1,2,3,4,5,6,8,7,9])
x=arr.reshape(3,3)
print(x)

[[1 2 3]
 [4 5 6]
 [8 7 9]]


In [15]:
# multi- 1D

y=b.reshape(-1)
print(y)

[ 1  2  3  4  5  6  7  8  9 10]


In [16]:
# iterating array---- i-iterating variable ,arr-sequential variable

for i in arr:
    print(i)

1
2
3
4
5
6
8
7
9


In [17]:
# jon array

a=np.array([10,20,30,40])
b=np.array([50,60,70,80])
#c=np.concatenate((a,b),axis=0) # row wize
c=np.stack((a,b),axis=1)       # column wize 
print(c)

[[10 50]
 [20 60]
 [30 70]
 [40 80]]


In [18]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
#c=np.concatenate((a,b),axis=1) # column wize
#c=np.vstack((a,b))          # vertical
#c=np.dstack((a,b))           # dimensional 
c=np.hstack((a,b))          # harizontal
print(c)

[[1 2 5 6]
 [3 4 7 8]]


In [19]:
a=np.array([50,10,30,20])
print(np.sort(a))

[10 20 30 50]


In [20]:
a=np.array([1,2,3,4,5])
print(np.zeros((3,3),dtype="int"))   # default float

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [21]:
print(np.zeros((5,3),dtype="int")) 

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


In [22]:
print(np.ones((4,2),dtype="float")) 

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [23]:
print(np.full((3,3),1))

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [24]:
print(np.arange(1,11))

[ 1  2  3  4  5  6  7  8  9 10]


In [25]:
# mathematical manipulation 

A=np.array([1,2,3,4])
B=np.array([2,4,6,8])
print(np.add(A,B))

[ 3  6  9 12]


In [26]:
A=np.array([1,2,3,4])
B=np.array([2,4,6,8])
print(np.subtract(A,B))

[-1 -2 -3 -4]


In [27]:
A=np.array([1,2,3,4])
B=np.array([2,4,6,8])
print(np.multiply(A,B))

[ 2  8 18 32]


In [28]:
A=np.array([1,2,3,4])
B=np.array([2,4,6,8])
print(np.divide(A,B))

[0.5 0.5 0.5 0.5]


In [29]:
arr1=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(np.sum(arr1,axis=1))   # Row wise sum up
print(np.sum(arr1,axis=0))   # column wise sum up
print(np.mean(arr1,axis=0))   # Row wise mean

[15 40]
[ 7  9 11 13 15]
[3.5 4.5 5.5 6.5 7.5]


In [30]:
ran=np.random.random((2,5))
ran

array([[0.16283075, 0.5529704 , 0.70553514, 0.40565046, 0.36718679],
       [0.22247071, 0.78462644, 0.99544443, 0.16756369, 0.43067802]])

In [31]:
# Random integer values array with in a specific range

ran2=np.random.randint(10,20,(3,5))
print(ran2)

[[13 13 11 10 11]
 [14 16 15 16 10]
 [16 13 12 17 10]]


In [32]:
# Array of evenly spaced values --> specifying the number of values required

d=np.linspace(10,30,5)
print(d)

[10. 15. 20. 25. 30.]


In [33]:
# Convert a list to numpy array

list2=[10,20,30,40,50]

np_array=np.asarray(list2) # asarray its converting the list to the array
print(np_array)
type(np_array)

[10 20 30 40 50]


numpy.ndarray

In [34]:
c=np.random.randint(10,90,(5,5))
print(c)

[[53 43 67 79 75]
 [36 77 55 62 33]
 [37 56 47 52 27]
 [77 63 78 19 89]
 [45 64 47 23 41]]


In [35]:
# array dimension 

print(c.shape)

(5, 5)


In [36]:
print(c.ndim)  # one or two dimensional

2


In [37]:
# Number of element in an array

print(c.size)

25


In [38]:
# Checking the data type of the values in the array

print(c.dtype)

int32
